<a href="https://colab.research.google.com/github/frncncantalejo/LinearAlgebra_2ndsem/blob/main/ASSIGNMENT_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 6 : Matrix Operations

Objectives
At the end of this activity you will be able to:

1.   Be familiar with the fundamental matrix operations.
2.   Apply the operations to solve intemrediate equations.
3.   Apply matrix algebra in engineering solutions.





In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Transposition

The transposition of a matrix is the process of rearranging the rows and columns. It is indicated by the symbol X'. The element in X's ith row and jth column will be placed in X's ith row and ith column. Assume that X is a 3x2 matrix and X' is a 2x3 matrix.

$$A = \begin{bmatrix} 1 & 2 & 5\\6 & 1 &3 \\ 4 & 6 & 4\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [ ]:
A = np.array([
  [1,2,5,],
  [6,1,3,],
  [4,6,4,]
])

A

array([[1, 2, 5],
       [6, 1, 3],
       [4, 6, 4]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[1, 6, 4],
       [2, 1, 6],
       [5, 3, 4]])

In [ ]:
AT2 = A.T
AT2

array([[1, 6, 4],
       [2, 1, 6],
       [5, 3, 4]])

In [ ]:
np.array_equiv(AT1, AT2)


True

In [ ]:
B = np.array([
    [5,3,9,3,3],
    [8,6,0,5,6],
    [4,2,1,3,2]
])
B.shape

(3, 5)

In [ ]:
np.transpose(B).shape

(5, 3)

In [ ]:
B.T.shape


(5, 3)

#Dot Product / Inner Product

The dot product is an algebraic operation that accepts two vectors of equal length and produces a scalar. The inner product is frequently used in Euclidean geometry to refer to the dot product among two vectors' Cartesian components.

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$


In [ ]:
X = np.array([
    [4,36,5],
    [1,32,7]
])

Y = np.array([
    [99,43,19],
    [45,34,53],
    [54,21,71]
])

In [ ]:
np.dot(X,Y)

array([[2286, 1501, 2339],
       [1917, 1278, 2212]])

In [ ]:
X.dot(Y)


array([[2286, 1501, 2339],
       [1917, 1278, 2212]])

In [ ]:
X @ Y


array([[2286, 1501, 2339],
       [1917, 1278, 2212]])

In [ ]:
np.matmul(X,Y)


array([[2286, 1501, 2339],
       [1917, 1278, 2212]])

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

$$A = \begin{bmatrix}6&3\\1&8\\-3&2\\6&5\end{bmatrix}, B = \begin{bmatrix}5&4\\6&3\\4&3\\5&6\end{bmatrix}, C = \begin{bmatrix}2&5&5&8\\4&1&6&6\end{bmatrix}$$


In [ ]:
A = np.array([
    [6, 3],
    [1, 8],
    [-3, 2],
    [6, 5],

])
B = np.array([
    [5,4],
    [6,3],
    [4,3],
    [5,6]
])
C = np.array([
    [2,5,5,8],
    [4,1,1,6]
])
print(A.shape)
print(B.shape)
print(C.shape)

(4, 2)
(4, 2)
(2, 4)


In [ ]:
A @ C

array([[ 24,  33,  33,  66],
       [ 34,  13,  13,  56],
       [  2, -13, -13, -12],
       [ 32,  35,  35,  78]])

In [ ]:
B @ C

array([[26, 29, 29, 64],
       [24, 33, 33, 66],
       [20, 23, 23, 50],
       [34, 31, 31, 76]])

In [ ]:
A @ B.T

array([[ 42,  45,  33,  48],
       [ 37,  30,  28,  53],
       [ -7, -12,  -6,  -3],
       [ 50,  51,  39,  60]])

In [ ]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

### Rule 2: Dot Product has special properties

Due to the fact that dot products are frequently used in matrix algebra, they possess numerous distinctive aspects that should be considered when formulating solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [9,3,4],
    [23,87,2],
    [45,62,45]
])
B = np.array([
    [76,21,43],
    [64,51,94],
    [15,43,38]
])
C = np.array([
    [21,74,52],
    [93,27,18],
    [57,32,29]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Determinant

The determinant of a square matrix is a specific number that may be derived from a square matrix and is denoted by the symbol.

In [ ]:
A = np.array([
    [13,44],
    [40,16]
])

np.linalg.det(A)

-1552.0000000000005

In [ ]:
B = np.array([
    [21,32,55,26],
    [-90,33,12,35],
    [13,15,48,23],
    [54,23,26,78]
])
np.linalg.det(B)

5803199.000000002

##Inverse

The inverse of a matrix is simply the reciprocal of the matrix, as we do in standard arithmetic when dealing with a single number. This reciprocal is used to solve equations and determine the values of unknown variables. The inverse of a matrix is the matrix that produces an identity matrix when multiplied by the original matrix

In [ ]:
M = np.array([
    [18,57],
    [-37, 85]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
N = np.array([
    [43,56,43,51,80,63,35],
    [90,44,10,81,52,24,52],
    [51,59,80,30,96,43,65],
    [14,76,14,45,83,43,11],
    [85,36,58,57,81,62,61],
    [-53,15,12,50,64,62,30],
    [-25,-35,21,62,51,40,61],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
squad = np.array([
    [8.0, 0.3, 2.0],
    [0.8, 0.4, 4.0],
    [0.6, 0.2, 7.0]
])
weights = np.array([
    [0.6, 0.4, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[6.12],
       [3.04],
       [4.64]])

##Activity

###Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
np.array([])

array([], dtype=float64)

## $A \cdot B \neq B \cdot A$
 

In [21]:
A = np.array([
        [13,62,2], 
        [45,54,61], 
        [76,58,19]
        ])
B = np.array([
        [74,98,49], 
        [48,63,11],
        [66,88,22]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += A[i][k] * B[k][j] 

print('A.B IS')
print(result)

A = np.array([
        [13,62,2], 
        [45,54,61], 
        [76,58,19]
        ])
B = np.array([
        [74,98,49], 
        [48,63,11],
        [66,88,22]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print('B.A IS')
print(result)
print('Therefore A.B is not equalt to B.A')

A.B IS
[[4070, 5356, 1363], [9948, 13180, 4141], [9662, 12774, 4780]]
B.A IS
[[9096, 12722, 7057], [4295, 7016, 4148], [6490, 10120, 5918]]
Therefore A.B is not equalt to B.A


## $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 

In [ ]:
A = np.array ([
      [43, 76, 21],
      [34, 56, 63],
      [57, 28, 19]
      ])
B = np.array ([
      [15, 32, 36],
      [14, 85, 66],
      [57, 38, 95]
      ])
C = np.array ([
      [90, 27, 31],
      [44, 52, 26],
      [87, 68, 59]
      ])


result = np.dot(B,C)
result = np.dot(A,result);
print("A.(B.C) is")
for r in result:
 print(r)

result = np.dot(A,B)
result = np.dot(result,C);
print("(A.B).C) is")
for r in result:
 print(r)


A.(B.C) is
[1386069 1109442  819551]
[1751033 1302019 1009122]
[922779 707002 536901]
(A.B).C) is
[1386069 1109442  819551]
[1751033 1302019 1009122]
[922779 707002 536901]


## $A\cdot(B+C) = A\cdot B + A\cdot C$
 

In [ ]:
A = np.array ([
      [76, 22, 53],
      [21, 65, 36],
      [75, 38, 29]
      ])
B = np.array ([
      [15, 27, 43],
      [44, 35, 86],
      [72, 86, 39]
      ])
C = np.array ([
      [19, 12, 63],
      [84, 53, 65],
      [75, 18, 49]
      ])

result = [[B[i][j] + C[i][j]  for j in range
(len(B[0]))] for i in range(len(B))]
result = np.dot(A,result)
print("A.(B+C) is")
for r in result:
 print(r)
result = np.dot(A,B)
result1 = np.dot(A,C)
result = [[result[i][j] + result1[i][j]  for j in range
(len(result[0]))] for i in range(len(result))]
print("A.B+A.C) is")
for r in result:
 print(r)

A.(B+C) is
[13191 10412 16042]
[14326 10283 15209]
[11677  9285 16240]
A.B+A.C) is
[13191, 10412, 16042]
[14326, 10283, 15209]
[11677, 9285, 16240]


## $(B+C)\cdot A = B\cdot A + C\cdot A$
 

In [ ]:
A = np.array ([
      [14, 86, 54],
      [45, 65, 45],
      [24, 18, 39]
      ])
B = np.array ([
      [13, 12, 53],
      [47, 75, 36],
      [76, 48, 39]
      ])
C = np.array ([
      [14, 32, 83],
      [94, 55, 66],
      [97, 48, 39]
      ])

result = [[B[i][j] + C[i][j]  for j in range
(len(B[0]))] for i in range(len(B))]
result = np.dot(result,A)
print("A.(B+C) is")
for r in result:
 print(r)
result = np.dot(B,A)
result1 = np.dot(C,A)
result = [[result[i][j] + result1[i][j]  for j in range
(len(result[0]))] for i in range(len(result))]
print("(A.B)+(A.C) is")
for r in result:
 print(r)

A.(B+C) is
[5622 7630 8742]
[10272 22412 17442]
[ 8614 22522 16704]
(A.B)+(A.C) is
[5622, 7630, 8742]
[10272, 22412, 17442]
[8614, 22522, 16704]


## $A\cdot I = A$

In [ ]:
A = np.array([
        [62, 74, 23], 
        [14 ,45, 46], 
        [37 ,48, 19]
        ])
B = np.array([
        [1,0,0], 
        [0,1,0],
        [0,0,1]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print (result)

[[62, 74, 23], [14, 45, 46], [37, 48, 19]]


## $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
        [34,27,53], 
        [64 ,35,56], 
        [87 ,38,29]
        ])
B = np.array([
        [0,0,0], 
        [0,0,0],
        [0,0,0]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print (result)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


##Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in healthcare?". 

Python is a well-known and popular programming language that is in great demand throughout the globe. It is applicable to a variety of fields, including data science, big data, programming, and application development. The students were able to practice and comprehend the concepts, syntax, and techniques of Python by completing this laboratory report. It entails familiarity with matrices and their relationship to linear equations, the ability to perform fundamental matrix operations, and the ability to program/translate matrix equations and operations. Learning the fundamentals undoubtedly aided in the acquisition of a load of new and useful characteristics. It will assist you in thinking more logically. You will be able to grasp complex ideas more easily and solve problems more effectively as a result of this course. 

At the end of the module, the students became capable of applying the knowledge about the language by involving themselves in doing several practices such as creating a corresponding matrix representing a linear combination, encoding and describing it as a matrix, expressing it as a linear combination, and Matrix Operations which includes Transposition, Dot Product/Inner Product and it’s rules, Determinant, and Inverse.  On the other hand, a task was performed. The program begins by being familiar with transposition, dot product, determinant and inverse. This familiarization aids us in putting our newfound knowledge into practice by allowing us to construct matrices that deal with multiplication properties. Moreover, a flow chart was created in relation to the tasks that discussed the methods and functions used. Furthermore, learning the fundamentals of programming helps develop mental abilities that are extremely useful in a variety of other areas of life. This engagement could assist people to make key patient care decisions and help us make huge changes. We'd look at the matrices first, then learn about each quality outcome and how competencies, abilities, and other aspects affect it. This setting would assist users to make vital patient care decisions. These matrices would also be useful for health care training, allowing us to broaden the scope of research and benefit the health care system. The ability to deconstruct a large problem into a series of increasingly small tasks, to abstract a solution in order to make it applicable to a larger set of problems, and even to develop fluency in logical analysis through debugging are all developmental skills that aid in decision making and critical thinking, which are necessary for solving healthcare problems.
