<a href="https://colab.research.google.com/github/frncncantalejo/LinearAlgebra_2ndsem/blob/main/CANTALEJO_Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 4 : Matrices

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

Rows and columns of data make up a Python matrix, which is a customized two-dimensional rectangular array. Mathematical phrases and symbols can also be included in a matrix. Mathematical and scientific computations can benefit greatly from the use of matrix data structures.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        6x - 15y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        5x+2y+8z \\ 
        4x -8y -2z \\
        -9x + 2y +6z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-5x+6y-z \\ 
        9w- 5x -3y +z \\
        6w -3x + 7y - 4z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 2 & 5 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 5 & 3 & 6 \\ 2 & -6 & -4 \\ -4 & 4 & 1\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 4 & -7 & -1 & 9 \\ 2 & -4 & 2 & -1\end{bmatrix}
$$

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be represented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
**bold text**Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [ ]:
def describe_mat(matrix):
  print(f'matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
A = np.array([
    [4, 8],
    [2, 0]
])
describe_mat(A)

matrix:
[[4 8]
 [2 0]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [4,1,9],
    [6,2,8]
])
describe_mat(G)

matrix:
[[4 1 9]
 [6 2 8]]

Shape:	(2, 3)
Rank:	2



In [ ]:
B = np.array([
    [2, 9],
    [3, 8],
    [2, 1]
])
describe_mat(B)

matrix:
[[2 9]
 [3 8]
 [2 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,5,9,1])
describe_mat(H)

matrix:
[1 5 9 1]

Shape:	(4,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.


BABAGUHIN

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

BABAGUHIN

In [ ]:

rowmatrix1D = np.array([
    1, 6, 5, -7
])
row_mat_2D = np.array([
    [1,9,2, -4]
])
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

matrix:
[ 1  6  5 -7]

Shape:	(4,)
Rank:	1

matrix:
[[ 1  9  2 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
col_mat = np.array([
    [10348727],
    [4],
    [9]
]) 
describe_mat(col_mat)

matrix:
[[10348727]
 [       4]
 [       9]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

BABAGUHIN

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [4,7,9],
    [6,0,1],
    [7,2,0]
])

non_square_mat = np.array([
    [5,2,9],
    [1,9,5]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

matrix:
[[4 7 9]
 [6 0 1]
 [7 2 0]]

Shape:	(3, 3)
Rank:	2

matrix:
[[5 2 9]
 [1 9 5]]

Shape:	(2, 3)
Rank:	2



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

BABAGUHIN

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((5,7))
zero_mat_sqr = np.zeros((2,4))
zero_mat_rct = np.zeros((9,3))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

BABAGUHIM

In [ ]:
ones_mat_row = np.ones((7,3))
ones_mat_sqr = np.ones((2,4))
ones_mat_rct = np.ones((2,6))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

BABAGUHIN

In [ ]:
np.array([
    [4,8,5],
    [4,7,3],
    [2,1,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[4, 8, 5],
       [4, 7, 3],
       [2, 1, 5]])

In [ ]:
d = np.diag([1,2,4,9])
d.shape[0] == d.shape[1]
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 9]])

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

BABAGUHIN

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

BABAGUHIN

In [ ]:
np.array([
    [4,7,9,2],
    [6,3,2,-2],
    [0,2,5,-8],
    [5,8,2,-3]
])

array([[ 4,  7,  9,  2],
       [ 6,  3,  2, -2],
       [ 0,  2,  5, -8],
       [ 5,  8,  2, -3]])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [9,2,1],
    [3,2,8],
    [2,9,2]
])

array([[9, 2, 1],
       [3, 2, 8],
       [2, 9, 2]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

$$
\theta=\begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0]== matrix.shape[1] else False
  print(f'matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
A = np.array([
    [1,2,1],
    [0,4,-1],
    [0,0,10]
])
describe_mat(A)

matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \left\{\begin{array}
1x_1 + 7x_2 +8x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
G = \left\{
    \begin{array}\
        l + 7m + 8n \\ 
        2l + 2m + 2n \\
        4l + 6m + 7n
    \end{array}
\right. $$

$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7 \end{bmatrix} \\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[4, 0, 0],
       [6, 2, 0]])

$$
H =\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7 \end{bmatrix} \\
$$

$$
H = \left\{
    \begin{array}\
        l \\ 
        2m + 2n \\
        4l + 6m + 7n
    \end{array}
\right. $$

# Matrix Algebra

### Addition

In [ ]:
A = np.array([
    [5,6,7],
    [7,3,6],
    [3,5,3]
])
B = np.array([
    [6,2,5],
    [1,4,2],
    [9,2,3],
])
A+B

array([[11,  8, 12],
       [ 8,  7,  8],
       [12,  7,  6]])

In [ ]:
5+A 

array([[10, 11],
       [12,  8],
       [ 8, 10]])

### Subtraction

In [ ]:
A-B

array([[-1,  4],
       [ 6, -1],
       [-6,  3]])

In [ ]:
8-B

array([[ 2,  6],
       [ 7,  4],
       [-1,  6]])

### Element-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[30, 12],
       [ 7, 12],
       [27, 10]])

In [ ]:
6*A

array([[30, 36],
       [42, 18],
       [18, 30]])

In [ ]:
A@B

array([[99, 48, 58],
       [99, 38, 59],
       [50, 32, 34]])

In [ ]:
alpha=5**-5
A/(alpha+B)

array([[0.83328889, 2.99952008, 1.39991041],
       [6.99776072, 0.74994   , 2.99952008],
       [0.33332148, 2.49960006, 0.99989334]])

In [ ]:
np.add(A,B)

array([[11,  8, 12],
       [ 8,  7,  8],
       [12,  7,  6]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function area

In [ ]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [ ]:
## Matrix declarations

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_desc(G)

[[1 7 8]
 [2 2 2]
 [4 6 7]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


In [ ]:
## Test Areas

### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The shape of both matrices are not same. Could not perform operations.')
        return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the given matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-wise division of the given matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)

In [ ]:
mat1 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat2 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_operations(mat1, mat2)

Matrix 1: [[1 7 8]
 [2 2 2]
 [4 6 7]]
Matrix 2: [[1 7 8]
 [2 2 2]
 [4 6 7]]
Sum of the given matrices:
[[ 2 14 16]
 [ 4  4  4]
 [ 8 12 14]]
Difference of the given matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-wise multiplication of the given matrices:
[[ 1 49 64]
 [ 4  4  4]
 [16 36 49]]
Element-wise division of the given matrices:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".